#!/usr/bin/env python3
"""agent-skills sync —— 把仓库里的 skills「编译」成 Claude Code 与 Codex CLI 各自认得的形式。

零第三方依赖,跨 Windows / macOS / Linux。子命令:
  install (默认)  按 manifest.json 安装插件依赖 + 复制自有 skill 到 ~/.claude/skills + 生成 Codex 路由
  collect          只读;列出本机「非插件提供」的候选 skill(给代理弹多选框用),--json 输出
  push --only a,b  把选中的本机 skill 收进仓库并 commit && push(反向贡献流程)
  add <路径>       把任意含 SKILL.md 的目录收进仓库(如 Codex 写的 prompt 目录)
  doctor           只报告:重复 / 残留 / 失效路径 / 待贡献候选,不擅自改
  uninstall        移除本工具装过的 skill + 清掉 Codex 路由区间

设计见 manifest.json 同目录。撞名策略:仓库优先;插件形态的技能集只「声明依赖」不复制。
"""
import argparse
import fnmatch
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

HOME = Path.home()
REPO = Path(__file__).resolve().parent
REPO_SKILLS = REPO / "skills"
MANIFEST = REPO / "manifest.json"

CLAUDE_DIR = HOME / ".claude"
CLAUDE_SKILLS = CLAUDE_DIR / "skills"
INSTALL_LEDGER = CLAUDE_SKILLS / ".agent-skills-installed.json"  # 记录本工具装过哪些 skill
PLUGINS_INSTALLED = CLAUDE_DIR / "plugins" / "installed_plugins.json"

CODEX_DIR = HOME / ".codex"
CODEX_AGENTS = CODEX_DIR / "AGENTS.md"

BEGIN = "<!-- AGENT-SKILLS:BEGIN (generated by sync.py — do not edit between markers) -->"
END = "<!-- AGENT-SKILLS:END -->"


# ---------- 基础工具 ----------

def log(msg):
    print(msg)


def warn(msg):
    print("⚠ " + msg, file=sys.stderr)


def load_manifest():
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def save_manifest(m):
    MANIFEST.write_text(json.dumps(m, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def read_frontmatter(skill_md):
    """极简 YAML frontmatter 解析,只取 name / description(不引 pyyaml)。"""
    name = desc = ""
    try:
        text = skill_md.read_text(encoding="utf-8")
    except OSError:
        return {"name": "", "description": ""}
    if not text.startswith("---"):
        return {"name": "", "description": ""}
    for line in text.splitlines()[1:]:
        if line.strip() == "---":
            break
        if ":" in line:
            k, _, v = line.partition(":")
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if k == "name":
                name = v
            elif k == "description":
                desc = v
    return {"name": name, "description": desc}


def has_claude_cli():
    return shutil.which("claude") is not None


def has_codex():
    return CODEX_DIR.exists() or shutil.which("codex") is not None


IGNORE = ("node_modules", "__pycache__", ".git")  # 依赖/缓存,不入库、不参与指纹比对


def dir_signature(d):
    """目录内容指纹:{相对路径: sha256},用于判断 skill 是否被本机改过(忽略 node_modules 等)。"""
    sig = {}
    for f in sorted(d.rglob("*")):
        parts = set(f.relative_to(d).parts)
        if f.is_file() and not (set(IGNORE) & parts) and f.suffix != ".pyc":
            sig[f.relative_to(d).as_posix()] = hashlib.sha256(f.read_bytes()).hexdigest()
    return sig


def copy_tree(src, dst, dry_run):
    if dry_run:
        log(f"  [dry-run] 复制 {src} -> {dst}")
        return
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(*IGNORE, "*.pyc"))


def run(cmd, dry_run):
    if dry_run:
        log("  [dry-run] $ " + " ".join(cmd))
        return 0
    return subprocess.run(cmd).returncode


# ---------- 插件信息 ----------

def installed_plugins():
    """返回 { 'plugin@marketplace': installPath(Path) }。"""
    out = {}
    if not PLUGINS_INSTALLED.exists():
        return out
    try:
        data = json.loads(PLUGINS_INSTALLED.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return out
    for key, entries in data.get("plugins", {}).items():
        if entries and entries[0].get("installPath"):
            out[key] = Path(entries[0]["installPath"])
    return out


def plugin_skill_index():
    """扫描所有已装插件的 skills,返回 { skill 目录名: {'plugin','md','fm'} }。"""
    index = {}
    for key, path in installed_plugins().items():
        sdir = path / "skills"
        if not sdir.is_dir():
            continue
        for child in sorted(sdir.iterdir()):
            md = child / "SKILL.md"
            if md.is_file():
                index[child.name] = {"plugin": key, "md": md, "fm": read_frontmatter(md)}
    return index


def plugin_skills_for_globs(globs):
    """按 manifest.codex.plugin_skills 的 '插件名/通配' 选出插件 skill 列表。"""
    chosen = []
    for key, path in installed_plugins().items():
        short = key.split("@", 1)[0]
        sdir = path / "skills"
        if not sdir.is_dir():
            continue
        for child in sorted(sdir.iterdir()):
            md = child / "SKILL.md"
            if not md.is_file():
                continue
            for g in globs:
                pre, _, pat = g.partition("/")
                if pre == short and fnmatch.fnmatch(child.name, pat or "*"):
                    fm = read_frontmatter(md)
                    chosen.append((fm["name"] or child.name, fm["description"], md))
                    break
    return chosen


# ---------- 账本 ----------

def load_ledger():
    if INSTALL_LEDGER.exists():
        try:
            return json.loads(INSTALL_LEDGER.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return []
    return []


def write_ledger(names, dry_run):
    if dry_run:
        log(f"  [dry-run] 写账本 {INSTALL_LEDGER} = {names}")
        return
    CLAUDE_SKILLS.mkdir(parents=True, exist_ok=True)
    INSTALL_LEDGER.write_text(json.dumps(sorted(names), indent=2) + "\n", encoding="utf-8")


# ---------- Codex 路由 ----------

def render_codex_block(entries):
    lines = [
        BEGIN,
        "## Available Skills (managed by agent-skills sync.py — do not edit between markers)",
        "",
        "When a task matches one of these skills, READ the linked file and follow it before acting.",
        "Skill files use Claude Code tool names; for Codex equivalents read the repo's "
        "`references/codex-tools.md`.",
        "",
    ]
    for name, desc, md in entries:
        lines.append(f"- **{name}** — {desc}")
        lines.append(f"  → {md}")
    lines.append(END)
    return "\n".join(lines)


def write_codex_router(m, dry_run):
    if not has_codex():
        log("未发现 ~/.codex 或 codex 命令,跳过 Codex 路由生成。")
        return
    entries = []
    for s in m.get("skills", []):
        md = REPO_SKILLS / s["name"] / "SKILL.md"
        if md.is_file():
            fm = read_frontmatter(md)
            entries.append((fm["name"] or s["name"], fm["description"], md))
    cfg = m.get("codex", {})
    if cfg.get("include_plugin_skills"):
        entries.extend(plugin_skills_for_globs(cfg.get("plugin_skills", [])))

    block = render_codex_block(entries)
    old = CODEX_AGENTS.read_text(encoding="utf-8") if CODEX_AGENTS.exists() else ""
    if BEGIN in old and END in old:
        head = old[: old.index(BEGIN)]
        tail = old[old.index(END) + len(END):]
        new = head + block + tail
    else:
        new = (old.rstrip() + "\n\n" + block + "\n") if old.strip() else (block + "\n")
    if dry_run:
        log(f"  [dry-run] 写 Codex 路由到 {CODEX_AGENTS}({len(entries)} 条)")
        return
    CODEX_DIR.mkdir(parents=True, exist_ok=True)
    CODEX_AGENTS.write_text(new, encoding="utf-8")
    log(f"已写 Codex 路由: {CODEX_AGENTS}({len(entries)} 条)")


# ---------- 子命令 ----------

def cmd_install(args):
    dry = args.dry_run
    m = load_manifest()

    # 1. 插件依赖(幂等)
    if has_claude_cli():
        for p in m.get("plugins", []):
            run(["claude", "plugin", "marketplace", "add", p["repo"]], dry)  # 已存在则忽略其报错
            run(["claude", "plugin", "install", f'{p["plugin"]}@{p["marketplace"]}'], dry)
    elif m.get("plugins"):
        warn("未找到 claude CLI,跳过插件安装(纯 Codex 机器?)。")

    # 2. 复制自有 skill
    ledger = set(load_ledger())
    plug_idx = plugin_skill_index()
    installed = []
    for s in m.get("skills", []):
        name = s["name"]
        src = REPO_SKILLS / name
        if not (src / "SKILL.md").is_file():
            warn(f"仓库缺少 skill: {name}(跳过)")
            continue
        dst = CLAUDE_SKILLS / name
        if dst.exists() and dir_signature(dst) == dir_signature(src):
            installed.append(name)  # 内容一致 → 纳管并跳过,避免无谓的 .bak/复制
            log(f"已是最新,跳过: {name}")
            continue
        if dst.exists() and name not in ledger:
            bak = dst.parent / (name + ".bak")
            if not dry:
                if bak.exists():
                    shutil.rmtree(bak)
                shutil.move(str(dst), str(bak))
            warn(f"{name}: 已存在非本工具管理的同名个人 skill,备份为 {name}.bak 后覆盖(仓库优先)。")
        if name in plug_idx:
            warn(f"{name}: 插件 {plug_idx[name]['plugin']} 也提供同名 skill(命名空间不同,仅提示)。")
        copy_tree(src, dst, dry)
        installed.append(name)
        log(f"已安装 skill: {name}")

    # 移除「曾由本工具安装、但 manifest 已删」的残留
    for old in ledger:
        if old not in installed:
            stale = CLAUDE_SKILLS / old
            if stale.exists():
                if not dry:
                    shutil.rmtree(stale)
                log(f"已移除已下线 skill: {old}")
    write_ledger(installed, dry)

    # 3. Codex 路由
    write_codex_router(m, dry)
    log("install 完成。" if not dry else "install dry-run 完成(未改动任何文件)。")


def _candidates():
    """本机 ~/.claude/skills 下『非插件提供』的 skill,作为贡献候选。"""
    m = load_manifest()
    repo_names = {s["name"] for s in m.get("skills", [])}
    plug_names = set(plugin_skill_index().keys())
    out = []
    if not CLAUDE_SKILLS.is_dir():
        return out
    for child in sorted(CLAUDE_SKILLS.iterdir()):
        if not child.is_dir() or child.name.startswith(".") or child.name.endswith(".bak"):
            continue
        md = child / "SKILL.md"
        if not md.is_file() or child.name in plug_names:
            continue
        fm = read_frontmatter(md)
        if child.name not in repo_names:
            status = "new"
        else:
            repo_dir = REPO_SKILLS / child.name
            status = "unchanged" if dir_signature(repo_dir) == dir_signature(child) else "modified"
        out.append({"name": child.name, "description": fm["description"],
                    "status": status, "path": str(child)})
    return out


def cmd_collect(args):
    cands = _candidates()
    if args.json:
        print(json.dumps(cands, ensure_ascii=False, indent=2))
        return
    if not cands:
        log("没有可贡献的候选(本机 ~/.claude/skills 里没有非插件、未收录的 skill)。")
        return
    log("待贡献候选(代理可据此弹多选框):")
    for c in cands:
        log(f"  [{c['status']:>9}] {c['name']} — {c['description']}")
    log("\n选好后让代理执行: python sync.py push --only <名1,名2>")


def _vendor_one(name, src_dir, m, plug_idx, force_vendor):
    """把 src_dir 收进仓库 skills/<name>;返回是否成功。"""
    md = src_dir / "SKILL.md"
    if not md.is_file():
        warn(f"{name}: {src_dir} 下没有 SKILL.md,跳过。")
        return False
    if name in plug_idx and not force_vendor:
        warn(f"{name}: 由插件 {plug_idx[name]['plugin']} 提供 —— 应加入 manifest.plugins 声明依赖,"
             f"而非 vendor 副本。确需用魔改版覆盖请加 --force-vendor。")
        return False
    fm = read_frontmatter(md)
    if not fm["name"] or not fm["description"]:
        warn(f"{name}: SKILL.md 缺 name/description frontmatter,跳过。")
        return False
    copy_tree(src_dir, REPO_SKILLS / name, dry_run=False)
    if name not in {s["name"] for s in m.get("skills", [])}:
        m.setdefault("skills", []).append({"name": name})
    return True


def cmd_push(args):
    m = load_manifest()
    plug_idx = plugin_skill_index()
    names = [n.strip() for n in args.only.split(",") if n.strip()]
    changed = []
    for name in names:
        if _vendor_one(name, CLAUDE_SKILLS / name, m, plug_idx, args.force_vendor):
            changed.append(name)
            log(f"已收进仓库: {name}")
    if not changed:
        log("没有任何 skill 被收录。")
        return
    save_manifest(m)
    subprocess.run(["git", "-C", str(REPO), "add", "-A"])
    rc = subprocess.run(["git", "-C", str(REPO), "commit", "-m",
                         "skills: add/update " + ", ".join(changed)]).returncode
    if rc != 0:
        log("git commit 未产生提交(可能无变更)。")
        return
    if subprocess.run(["git", "-C", str(REPO), "push"]).returncode == 0:
        log("已提交并推送。其他机器执行: git pull && python sync.py")
    else:
        log("已提交;push 失败(可能未配置远端)。请手动 git push。")


def cmd_add(args):
    m = load_manifest()
    plug_idx = plugin_skill_index()
    src = Path(args.path).expanduser().resolve()
    name = args.name or src.name
    if _vendor_one(name, src, m, plug_idx, args.force_vendor):
        save_manifest(m)
        log(f"已收进仓库并登记 manifest: {name}")
        log("下一步: git -C %s add -A && git commit && git push" % REPO)


def cmd_doctor(args):
    plug_idx = plugin_skill_index()
    log("== agent-skills doctor ==")

    # ① 个人 skill 与插件同名重复
    dups = []
    if CLAUDE_SKILLS.is_dir():
        for child in sorted(CLAUDE_SKILLS.iterdir()):
            if child.is_dir() and child.name in plug_idx:
                dups.append((child.name, plug_idx[child.name]["plugin"]))
    log(f"\n① 个人 skill 与已装插件同名重复({len(dups)}):")
    for n, p in dups:
        log(f"   - {n}  (插件 {p} 也提供;可考虑删掉 ~/.claude/skills/{n})")

    # ② 账本里有、但 manifest 已删 / 目录缺失
    m = load_manifest()
    repo_names = {s["name"] for s in m.get("skills", [])}
    log("\n② 本工具装过、但已下线或缺失的残留:")
    for old in load_ledger():
        if old not in repo_names:
            log(f"   - {old}  (manifest 已无此项;uninstall 或重跑 install 会清理)")

    # ③ Codex 路由失效路径
    log("\n③ Codex 路由里指向不存在的文件:")
    if CODEX_AGENTS.exists():
        txt = CODEX_AGENTS.read_text(encoding="utf-8")
        for line in txt.splitlines():
            line = line.strip()
            if line.startswith("→ "):
                p = Path(line[2:].strip())
                if not p.exists():
                    log(f"   - {p}")
    else:
        log("   (无 ~/.codex/AGENTS.md)")

    # ④ 待贡献候选
    cands = _candidates()
    log(f"\n④ 待贡献候选({len(cands)};可走 push 流程):")
    for c in cands:
        log(f"   - [{c['status']}] {c['name']}")


def cmd_uninstall(args):
    dry = args.dry_run
    for name in load_ledger():
        d = CLAUDE_SKILLS / name
        if d.exists():
            if not dry:
                shutil.rmtree(d)
            log(f"移除 skill: {name}")
    if not dry and INSTALL_LEDGER.exists():
        INSTALL_LEDGER.unlink()
    # 清掉 Codex 路由区间
    if CODEX_AGENTS.exists():
        txt = CODEX_AGENTS.read_text(encoding="utf-8")
        if BEGIN in txt and END in txt:
            new = txt[: txt.index(BEGIN)].rstrip() + "\n" + txt[txt.index(END) + len(END):].lstrip()
            if not dry:
                CODEX_AGENTS.write_text(new, encoding="utf-8")
            log("已清除 Codex 路由区间。")
    log("uninstall 完成。" if not dry else "uninstall dry-run 完成。")


def main():
    ap = argparse.ArgumentParser(description="agent-skills sync")
    sub = ap.add_subparsers(dest="cmd")

    pi = sub.add_parser("install", help="按 manifest 安装(默认)")
    pi.add_argument("--dry-run", action="store_true")
    pi.set_defaults(func=cmd_install)

    pc = sub.add_parser("collect", help="列出待贡献候选")
    pc.add_argument("--json", action="store_true")
    pc.set_defaults(func=cmd_collect)

    pp = sub.add_parser("push", help="收录选中 skill 并 commit&push")
    pp.add_argument("--only", required=True, help="逗号分隔的 skill 名")
    pp.add_argument("--force-vendor", action="store_true")
    pp.set_defaults(func=cmd_push)

    pa = sub.add_parser("add", help="收录任意路径下含 SKILL.md 的目录")
    pa.add_argument("path")
    pa.add_argument("--name")
    pa.add_argument("--force-vendor", action="store_true")
    pa.set_defaults(func=cmd_add)

    pd = sub.add_parser("doctor", help="只报告问题,不改动")
    pd.set_defaults(func=cmd_doctor)

    pu = sub.add_parser("uninstall", help="移除本工具装过的 skill + Codex 路由")
    pu.add_argument("--dry-run", action="store_true")
    pu.set_defaults(func=cmd_uninstall)

    args = ap.parse_args()
    if not args.cmd:
        args = ap.parse_args(["install"])
    args.func(args)


if __name__ == "__main__":
    main()
