#!/usr/bin/env python3
"""agent-skills sync —— 把仓库里的 skills「编译」成 Claude Code 与 Codex CLI 各自认得的形式。

子命令:
  install (默认)  装插件依赖 + 按「本机启用集」复制自有 skill 到 ~/.claude/skills + 生成 Codex 路由。
                   交互式 TUI(分类 tab + 复选框)选启用哪些;无 TTY/--no-tui/未装 textual 时降级。
  collect          只读;列出本机「非插件提供」的候选 skill,--json 输出。
  push             交互式(分类:新增/更新 + 复选框)挑本机 skill 收进仓库并 commit && push;
                   `--only a,b` 走非交互(给代理/脚本)。
  add <路径>       把任意含 SKILL.md 的目录收进仓库(如 Codex 写的 prompt 目录)。
  doctor           只报告:重复 / 残留 / 失效路径 / 待贡献候选,不擅自改。
  uninstall        移除本工具装过的 skill + 清掉 Codex 路由区间。

TUI 用 textual(见 requirements.txt);缺失或非交互时自动降级为 stdlib 编号选择,核心逻辑零依赖。
撞名策略:仓库优先;插件形态的技能集只「声明依赖」不复制。
"""
import argparse
import fnmatch
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

HOME = Path.home()
REPO = Path(__file__).resolve().parent
REPO_SKILLS = REPO / "skills"
MANIFEST = REPO / "manifest.json"

CLAUDE_DIR = HOME / ".claude"
CLAUDE_SKILLS = CLAUDE_DIR / "skills"
INSTALL_LEDGER = CLAUDE_SKILLS / ".agent-skills-installed.json"  # 记录本工具装过哪些 skill
PLUGINS_INSTALLED = CLAUDE_DIR / "plugins" / "installed_plugins.json"

CODEX_DIR = HOME / ".codex"
CODEX_AGENTS = CODEX_DIR / "AGENTS.md"

ENABLED_SET = HOME / ".agent-skills" / "selection.json"  # 本机启用集(per-machine,不入共享 manifest)

# 启用集 value 编码:自有 skill 与插件 skill 共用一个集合,用前缀区分
OWN = "own::"
PLG = "plugin::"

BEGIN = "<!-- AGENT-SKILLS:BEGIN (generated by sync.py — do not edit between markers) -->"
END = "<!-- AGENT-SKILLS:END -->"


# ---------- 基础工具 ----------

def log(msg):
    print(msg)


def warn(msg):
    print("⚠ " + msg, file=sys.stderr)


def load_manifest():
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def save_manifest(m):
    MANIFEST.write_text(json.dumps(m, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def read_frontmatter(skill_md):
    """极简 YAML frontmatter 解析,只取 name / description(不引 pyyaml)。"""
    name = desc = ""
    try:
        text = skill_md.read_text(encoding="utf-8")
    except OSError:
        return {"name": "", "description": ""}
    if not text.startswith("---"):
        return {"name": "", "description": ""}
    for line in text.splitlines()[1:]:
        if line.strip() == "---":
            break
        if ":" in line:
            k, _, v = line.partition(":")
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if k == "name":
                name = v
            elif k == "description":
                desc = v
    return {"name": name, "description": desc}


def has_claude_cli():
    return shutil.which("claude") is not None


def has_codex():
    return CODEX_DIR.exists() or shutil.which("codex") is not None


IGNORE = ("node_modules", "__pycache__", ".git")  # 依赖/缓存,不入库、不参与指纹比对


def dir_signature(d):
    """目录内容指纹:{相对路径: sha256},用于判断 skill 是否被本机改过(忽略 node_modules 等)。"""
    sig = {}
    for f in sorted(d.rglob("*")):
        parts = set(f.relative_to(d).parts)
        if f.is_file() and not (set(IGNORE) & parts) and f.suffix != ".pyc":
            sig[f.relative_to(d).as_posix()] = hashlib.sha256(f.read_bytes()).hexdigest()
    return sig


def copy_tree(src, dst, dry_run):
    if dry_run:
        log(f"  [dry-run] 复制 {src} -> {dst}")
        return
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns(*IGNORE, "*.pyc"))


def run(cmd, dry_run):
    if dry_run:
        log("  [dry-run] $ " + " ".join(cmd))
        return 0
    return subprocess.run(cmd).returncode


# ---------- 插件信息 ----------

def installed_plugins():
    """返回 { 'plugin@marketplace': installPath(Path) }。"""
    out = {}
    if not PLUGINS_INSTALLED.exists():
        return out
    try:
        data = json.loads(PLUGINS_INSTALLED.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return out
    for key, entries in data.get("plugins", {}).items():
        if entries and entries[0].get("installPath"):
            out[key] = Path(entries[0]["installPath"])
    return out


def plugin_skill_index():
    """扫描所有已装插件的 skills,返回 { skill 目录名: {'plugin','md','fm'} }。"""
    index = {}
    for key, path in installed_plugins().items():
        sdir = path / "skills"
        if not sdir.is_dir():
            continue
        for child in sorted(sdir.iterdir()):
            md = child / "SKILL.md"
            if md.is_file():
                index[child.name] = {"plugin": key, "md": md, "fm": read_frontmatter(md)}
    return index


# ---------- 账本 ----------

def load_ledger():
    if INSTALL_LEDGER.exists():
        try:
            return json.loads(INSTALL_LEDGER.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return []
    return []


def write_ledger(names, dry_run):
    if dry_run:
        log(f"  [dry-run] 写账本 {INSTALL_LEDGER} = {names}")
        return
    CLAUDE_SKILLS.mkdir(parents=True, exist_ok=True)
    INSTALL_LEDGER.write_text(json.dumps(sorted(names), indent=2) + "\n", encoding="utf-8")


# ---------- Codex 路由 ----------

def render_codex_block(entries):
    lines = [
        BEGIN,
        "## Available Skills (managed by agent-skills sync.py — do not edit between markers)",
        "",
        "When a task matches one of these skills, READ the linked file and follow it before acting.",
        "Skill files use Claude Code tool names; for Codex equivalents read the repo's "
        "`references/codex-tools.md`.",
        "",
    ]
    for name, desc, md in entries:
        lines.append(f"- **{name}** — {desc}")
        lines.append(f"  → {md}")
    lines.append(END)
    return "\n".join(lines)


def write_codex_router(entries, dry_run):
    """entries: [(name, description, md_path), ...](由 install 按本机启用集算好)。"""
    if not has_codex():
        log("未发现 ~/.codex 或 codex 命令,跳过 Codex 路由生成。")
        return
    block = render_codex_block(entries)
    old = CODEX_AGENTS.read_text(encoding="utf-8") if CODEX_AGENTS.exists() else ""
    if BEGIN in old and END in old:
        head = old[: old.index(BEGIN)]
        tail = old[old.index(END) + len(END):]
        new = head + block + tail
    else:
        new = (old.rstrip() + "\n\n" + block + "\n") if old.strip() else (block + "\n")
    if dry_run:
        log(f"  [dry-run] 写 Codex 路由到 {CODEX_AGENTS}({len(entries)} 条)")
        return
    CODEX_DIR.mkdir(parents=True, exist_ok=True)
    CODEX_AGENTS.write_text(new, encoding="utf-8")
    log(f"已写 Codex 路由: {CODEX_AGENTS}({len(entries)} 条)")


# ---------- 分类 / 启用集 / 选择(TUI 或降级) ----------

def category_of(name, source, manifest_entry):
    """混合分类:manifest 给了 category 用之;否则按来源——自有→vendored,插件→插件短名。"""
    if manifest_entry and manifest_entry.get("category"):
        return manifest_entry["category"]
    if source == "own":
        return "vendored"
    return source  # 插件短名,如 superpowers / cloudflare


def selected_plugin_skills(globs):
    """按 manifest.codex.plugin_skills 的 '插件名/通配' 选出插件 skill,返回 [{name,desc,md,plugin,short}]。"""
    out = []
    for key, path in installed_plugins().items():
        short = key.split("@", 1)[0]
        sdir = path / "skills"
        if not sdir.is_dir():
            continue
        for child in sorted(sdir.iterdir()):
            md = child / "SKILL.md"
            if not md.is_file():
                continue
            for g in globs:
                pre, _, pat = g.partition("/")
                if pre == short and fnmatch.fnmatch(child.name, pat or "*"):
                    fm = read_frontmatter(md)
                    out.append({"name": fm["name"] or child.name, "desc": fm["description"],
                                "md": md, "plugin": key, "short": short})
                    break
    return out


def build_install_catalog(m):
    """构建 install 目录:返回 (catalog, meta)。
    catalog = [(分类, [(value, label)]), ...];meta = {value: {kind,name,desc,md}}。"""
    plug_idx = plugin_skill_index()
    groups, meta = {}, {}

    def add(cat, value, label, info):
        groups.setdefault(cat, []).append((value, label))
        meta[value] = info

    for s in m.get("skills", []):                       # 自有 skill
        name = s["name"]
        md = REPO_SKILLS / name / "SKILL.md"
        if not md.is_file():
            continue
        fm = read_frontmatter(md)
        tag = "  [dup]" if name in plug_idx else ""
        add(category_of(name, "own", s), OWN + name,
            f"{name} — {(fm['description'] or '')[:64]}{tag}",
            {"kind": "own", "name": name, "desc": fm["description"], "md": md})

    cfg = m.get("codex", {})                            # 插件 skill(按 codex.plugin_skills 选)
    if cfg.get("include_plugin_skills"):
        for ps in selected_plugin_skills(cfg.get("plugin_skills", [])):
            add(category_of(ps["name"], ps["short"], None),
                f"{PLG}{ps['plugin']}::{ps['name']}",
                f"{ps['name']} — {(ps['desc'] or '')[:60]}  [插件]",
                {"kind": "plugin", "name": ps["name"], "desc": ps["desc"], "md": ps["md"]})

    catalog = sorted(groups.items(), key=lambda kv: (kv[0] != "vendored", kv[0]))  # 自有分类在前
    return catalog, meta


def load_enabled():
    if ENABLED_SET.exists():
        try:
            return set(json.loads(ENABLED_SET.read_text(encoding="utf-8")))
        except (OSError, ValueError):
            return None
    return None


def save_enabled(values):
    ENABLED_SET.parent.mkdir(parents=True, exist_ok=True)
    ENABLED_SET.write_text(json.dumps(sorted(values), indent=2, ensure_ascii=False) + "\n",
                           encoding="utf-8")


def _interactive():
    return sys.stdin.isatty() and sys.stdout.isatty()


def choose_set(catalog, preselected, title, no_tui):
    """统一选择入口:TUI → 降级编号 → 非交互直接用 preselected。返回勾选 value 集合。"""
    if not catalog:
        return set()
    if not _interactive():
        return set(preselected)  # headless / 管道 / 代理:不阻塞,用预选(启用集或默认)
    if not no_tui:
        try:
            from tui import choose
            r = choose(catalog, preselected, title)
            return set(preselected) if r is None else set(r)  # 取消 → 不改动
        except Exception as e:  # textual 缺失或渲染失败 → 降级
            warn(f"TUI 不可用({e}),降级为编号选择。")
    return _numbered_choose(catalog, preselected, title)


def _numbered_choose(catalog, preselected, title):
    log(title)
    idx_to_val, state, n = {}, {}, 0
    for cat, items in catalog:
        log(f"\n== {cat} ==")
        for value, label in items:
            n += 1
            state[value] = value in preselected
            idx_to_val[n] = value
            log(f"  {n:>3} [{'x' if state[value] else ' '}] {label}")
    log("\n输入要切换勾选的编号(逗号分隔),回车保持现状,q 取消:")
    try:
        line = input("> ").strip()
    except EOFError:
        line = ""
    if line.lower() == "q":
        return set(preselected)
    for tok in line.replace(" ", "").split(","):
        if tok.isdigit() and int(tok) in idx_to_val:
            v = idx_to_val[int(tok)]
            state[v] = not state[v]
    return {v for v, on in state.items() if on}


def _git_commit_push(changed):
    subprocess.run(["git", "-C", str(REPO), "add", "-A"])
    rc = subprocess.run(["git", "-C", str(REPO), "commit", "-m",
                         "skills: add/update " + ", ".join(changed)]).returncode
    if rc != 0:
        log("git commit 未产生提交(可能无变更)。")
        return
    if subprocess.run(["git", "-C", str(REPO), "push"]).returncode == 0:
        log("已提交并推送。其他机器执行: git pull && python sync.py")
    else:
        log("已提交;push 失败(可能未配置远端)。请手动 git push。")


# ---------- 子命令 ----------

def cmd_install(args):
    dry = args.dry_run
    m = load_manifest()

    # 1. 插件依赖(幂等)
    if has_claude_cli():
        for p in m.get("plugins", []):
            run(["claude", "plugin", "marketplace", "add", p["repo"]], dry)  # 已存在则忽略其报错
            run(["claude", "plugin", "install", f'{p["plugin"]}@{p["marketplace"]}'], dry)
    elif m.get("plugins"):
        warn("未找到 claude CLI,跳过插件安装(纯 Codex 机器?)。")

    # 2. 构建目录 + 选「本机启用集」
    catalog, meta = build_install_catalog(m)
    all_values = set(meta)
    saved = load_enabled()
    preselected = (saved & all_values) if saved is not None else set(all_values)  # 首次=全选
    if dry:
        selected = preselected            # dry-run 不弹交互,按当前启用集预览
    else:
        selected = choose_set(catalog, preselected, "选择本机要启用的 skills", args.no_tui)
        save_enabled(selected)

    # 3. 应用:自有 skill 勾选→复制、取消→移除(仅动本工具管理的)
    ledger = set(load_ledger())
    plug_idx = plugin_skill_index()
    own = {v: meta[v]["name"] for v in all_values if meta[v]["kind"] == "own"}
    installed = []
    for v, name in sorted(own.items(), key=lambda kv: kv[1]):
        src, dst = REPO_SKILLS / name, CLAUDE_SKILLS / name
        if v in selected:
            if dst.exists() and dir_signature(dst) == dir_signature(src):
                installed.append(name)
                log(f"已是最新,跳过: {name}")
                continue
            if dst.exists() and name not in ledger:
                bak = dst.parent / (name + ".bak")
                if not dry:
                    if bak.exists():
                        shutil.rmtree(bak)
                    shutil.move(str(dst), str(bak))
                warn(f"{name}: 已存在非本工具管理的同名个人 skill,备份为 {name}.bak 后覆盖(仓库优先)。")
            if name in plug_idx:
                warn(f"{name}: 插件 {plug_idx[name]['plugin']} 也提供同名 skill(仅提示)。")
            copy_tree(src, dst, dry)
            installed.append(name)
            log(f"已启用 skill: {name}")
        elif name in ledger and dst.exists():            # 取消勾选且本工具装的 → 移除
            if not dry:
                shutil.rmtree(dst)
            log(f"已停用(移除)skill: {name}")

    # 移除「曾装、但 manifest 已删(目录里已无)」的残留
    own_names = set(own.values())
    for old in ledger:
        if old not in own_names and (CLAUDE_SKILLS / old).exists():
            if not dry:
                shutil.rmtree(CLAUDE_SKILLS / old)
            log(f"已移除已下线 skill: {old}")
    write_ledger(installed, dry)

    # 4. Codex 路由:只列勾选项(自有指 repo、插件指缓存正本)
    entries = []
    for cat, items in catalog:
        for value, _ in items:
            if value in selected:
                info = meta[value]
                entries.append((info["name"], info["desc"], info["md"]))
    off = [meta[v]["name"] for v in all_values if meta[v]["kind"] == "plugin" and v not in selected]
    if off:
        log(f"注:取消勾选的插件 skill 仅从 Codex 路由移除,Claude 仍由插件提供:{', '.join(off)}")
    write_codex_router(entries, dry)
    log("install 完成。" if not dry else "install dry-run 完成(未改动任何文件)。")


def _candidates():
    """本机 ~/.claude/skills 下『非插件提供』的 skill,作为贡献候选。"""
    m = load_manifest()
    repo_names = {s["name"] for s in m.get("skills", [])}
    plug_names = set(plugin_skill_index().keys())
    out = []
    if not CLAUDE_SKILLS.is_dir():
        return out
    for child in sorted(CLAUDE_SKILLS.iterdir()):
        if not child.is_dir() or child.name.startswith(".") or child.name.endswith(".bak"):
            continue
        md = child / "SKILL.md"
        if not md.is_file() or child.name in plug_names:
            continue
        fm = read_frontmatter(md)
        if child.name not in repo_names:
            status = "new"
        else:
            repo_dir = REPO_SKILLS / child.name
            status = "unchanged" if dir_signature(repo_dir) == dir_signature(child) else "modified"
        out.append({"name": child.name, "description": fm["description"],
                    "status": status, "path": str(child)})
    return out


def cmd_collect(args):
    cands = _candidates()
    if args.json:
        print(json.dumps(cands, ensure_ascii=False, indent=2))
        return
    if not cands:
        log("没有可贡献的候选(本机 ~/.claude/skills 里没有非插件、未收录的 skill)。")
        return
    log("待贡献候选(代理可据此弹多选框):")
    for c in cands:
        log(f"  [{c['status']:>9}] {c['name']} — {c['description']}")
    log("\n选好后让代理执行: python sync.py push --only <名1,名2>")


def _vendor_one(name, src_dir, m, plug_idx, force_vendor):
    """把 src_dir 收进仓库 skills/<name>;返回是否成功。"""
    md = src_dir / "SKILL.md"
    if not md.is_file():
        warn(f"{name}: {src_dir} 下没有 SKILL.md,跳过。")
        return False
    if name in plug_idx and not force_vendor:
        warn(f"{name}: 由插件 {plug_idx[name]['plugin']} 提供 —— 应加入 manifest.plugins 声明依赖,"
             f"而非 vendor 副本。确需用魔改版覆盖请加 --force-vendor。")
        return False
    fm = read_frontmatter(md)
    if not fm["name"] or not fm["description"]:
        warn(f"{name}: SKILL.md 缺 name/description frontmatter,跳过。")
        return False
    copy_tree(src_dir, REPO_SKILLS / name, dry_run=False)
    if name not in {s["name"] for s in m.get("skills", [])}:
        m.setdefault("skills", []).append({"name": name})
    return True


def _push_catalog():
    """把本机候选按『新增 / 更新』分类,返回 (catalog, preselected_names, info)。"""
    by = {"新增(repo 没有)": [], "更新(已改动)": []}
    info = {}
    for c in _candidates():
        info[c["name"]] = c
        cat = {"new": "新增(repo 没有)", "modified": "更新(已改动)"}.get(c["status"])
        if cat:
            by[cat].append(c["name"])
    catalog, preselected = [], set()
    for cat, names in by.items():
        items = []
        for name in sorted(names):
            items.append((name, f"{name} — {(info[name]['description'] or '')[:64]}"))
            preselected.add(name)        # 新增/更新默认勾选
        if items:
            catalog.append((cat, items))
    return catalog, preselected, info


def cmd_push(args):
    m = load_manifest()
    plug_idx = plugin_skill_index()

    if args.only is not None:                        # 非交互(代理/脚本);空串=不收录任何
        names = [n.strip() for n in args.only.split(",") if n.strip()]
    else:                                            # 交互:分类 + 复选框
        catalog, preselected, _ = _push_catalog()
        if not catalog:
            log("没有可贡献的候选(本机没有新增/改动且非插件的 skill)。")
            return
        names = sorted(choose_set(catalog, preselected, "选择要提交到仓库的 skills", args.no_tui))

    changed = []
    for name in names:
        if _vendor_one(name, CLAUDE_SKILLS / name, m, plug_idx, args.force_vendor):
            changed.append(name)
            log(f"已收进仓库: {name}")
    if not changed:
        log("没有任何 skill 被收录。")
        return
    save_manifest(m)
    _git_commit_push(changed)


def cmd_add(args):
    m = load_manifest()
    plug_idx = plugin_skill_index()
    src = Path(args.path).expanduser().resolve()
    name = args.name or src.name
    if _vendor_one(name, src, m, plug_idx, args.force_vendor):
        save_manifest(m)
        log(f"已收进仓库并登记 manifest: {name}")
        log("下一步: git -C %s add -A && git commit && git push" % REPO)


def cmd_doctor(args):
    plug_idx = plugin_skill_index()
    log("== agent-skills doctor ==")

    # ① 个人 skill 与插件同名重复
    dups = []
    if CLAUDE_SKILLS.is_dir():
        for child in sorted(CLAUDE_SKILLS.iterdir()):
            if child.is_dir() and child.name in plug_idx:
                dups.append((child.name, plug_idx[child.name]["plugin"]))
    log(f"\n① 个人 skill 与已装插件同名重复({len(dups)}):")
    for n, p in dups:
        log(f"   - {n}  (插件 {p} 也提供;可考虑删掉 ~/.claude/skills/{n})")

    # ② 账本里有、但 manifest 已删 / 目录缺失
    m = load_manifest()
    repo_names = {s["name"] for s in m.get("skills", [])}
    log("\n② 本工具装过、但已下线或缺失的残留:")
    for old in load_ledger():
        if old not in repo_names:
            log(f"   - {old}  (manifest 已无此项;uninstall 或重跑 install 会清理)")

    # ③ Codex 路由失效路径
    log("\n③ Codex 路由里指向不存在的文件:")
    if CODEX_AGENTS.exists():
        txt = CODEX_AGENTS.read_text(encoding="utf-8")
        for line in txt.splitlines():
            line = line.strip()
            if line.startswith("→ "):
                p = Path(line[2:].strip())
                if not p.exists():
                    log(f"   - {p}")
    else:
        log("   (无 ~/.codex/AGENTS.md)")

    # ④ 待贡献候选
    cands = _candidates()
    log(f"\n④ 待贡献候选({len(cands)};可走 push 流程):")
    for c in cands:
        log(f"   - [{c['status']}] {c['name']}")


def cmd_uninstall(args):
    dry = args.dry_run
    for name in load_ledger():
        d = CLAUDE_SKILLS / name
        if d.exists():
            if not dry:
                shutil.rmtree(d)
            log(f"移除 skill: {name}")
    if not dry and INSTALL_LEDGER.exists():
        INSTALL_LEDGER.unlink()
    # 清掉 Codex 路由区间
    if CODEX_AGENTS.exists():
        txt = CODEX_AGENTS.read_text(encoding="utf-8")
        if BEGIN in txt and END in txt:
            new = txt[: txt.index(BEGIN)].rstrip() + "\n" + txt[txt.index(END) + len(END):].lstrip()
            if not dry:
                CODEX_AGENTS.write_text(new, encoding="utf-8")
            log("已清除 Codex 路由区间。")
    log("uninstall 完成。" if not dry else "uninstall dry-run 完成。")


def main():
    ap = argparse.ArgumentParser(description="agent-skills sync")
    sub = ap.add_subparsers(dest="cmd")

    pi = sub.add_parser("install", help="按 manifest 安装(默认);交互选本机启用集")
    pi.add_argument("--dry-run", action="store_true")
    pi.add_argument("--no-tui", action="store_true", help="不弹 TUI,改用编号选择/启用集")
    pi.set_defaults(func=cmd_install)

    pc = sub.add_parser("collect", help="列出待贡献候选")
    pc.add_argument("--json", action="store_true")
    pc.set_defaults(func=cmd_collect)

    pp = sub.add_parser("push", help="挑本机 skill 收录并 commit&push(默认交互)")
    pp.add_argument("--only", help="逗号分隔的 skill 名(给定则走非交互)")
    pp.add_argument("--no-tui", action="store_true", help="不弹 TUI,改用编号选择")
    pp.add_argument("--force-vendor", action="store_true")
    pp.set_defaults(func=cmd_push)

    pa = sub.add_parser("add", help="收录任意路径下含 SKILL.md 的目录")
    pa.add_argument("path")
    pa.add_argument("--name")
    pa.add_argument("--force-vendor", action="store_true")
    pa.set_defaults(func=cmd_add)

    pd = sub.add_parser("doctor", help="只报告问题,不改动")
    pd.set_defaults(func=cmd_doctor)

    pu = sub.add_parser("uninstall", help="移除本工具装过的 skill + Codex 路由")
    pu.add_argument("--dry-run", action="store_true")
    pu.set_defaults(func=cmd_uninstall)

    args = ap.parse_args()
    if not args.cmd:
        args = ap.parse_args(["install"])
    args.func(args)


if __name__ == "__main__":
    main()
